# Site settings
author: Kelly
title: Software Engineering Bootcamp Blog
header-img: img/home-bg.png
email: kpowers.nj@gmail.com
copyright_name: Kelly
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Online Full Time Program 2020
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kellypowers

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
